/*
Copyright 2022 The Matrix.org Foundation C.I.C.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import { useEffect, useState } from "react";
import { EventType } from "matrix-js-sdk/src/@types/event";
import { MatrixEvent } from "matrix-js-sdk/src/models/event";
import { Room } from "matrix-js-sdk/src/models/room";
import { RoomStateEvent } from "matrix-js-sdk/src/models/room-state";
import { parseTopicContent, TopicState } from "matrix-js-sdk/src/content-helpers";
import { MRoomTopicEventContent } from "matrix-js-sdk/src/@types/topic";
import { Optional } from "matrix-events-sdk";

import { useTypedEventEmitter } from "../useEventEmitter";
import { _t } from "../../languageHandler";

// Matches the default topic generated by the server when a class room is created,
// including older variants that differ only by capitalization.
const DEFAULT_TOPIC_REGEX = /^(?:A Room for|Uma sala para) (.+)$/i;

/**
 * The server stores the default topic in a single language, so translate it
 * on the client according to the language selected by the user.
 */
export const localizeDefaultTopic = (topic: string): string => {
    const match = DEFAULT_TOPIC_REGEX.exec(topic);
    return match ? _t("A Room for %(name)s", { name: match[1] }) : topic;
};

export const getTopic = (room: Room): Optional<TopicState> => {
    const content = room?.currentState?.getStateEvents(EventType.RoomTopic, "")?.getContent<MRoomTopicEventContent>();
    return !!content ? parseTopicContent(content) : null;
};

export function useTopic(room: Room): Optional<TopicState> {
    const [topic, setTopic] = useState(getTopic(room));
    useTypedEventEmitter(room.currentState, RoomStateEvent.Events, (ev: MatrixEvent) => {
        if (ev.getType() !== EventType.RoomTopic) return;
        setTopic(getTopic(room));
    });
    useEffect(() => {
        setTopic(getTopic(room));
    }, [room]);

    if (!topic) return topic;
    const localizedText = localizeDefaultTopic(topic.text);
    // A localized default topic is plain text, so drop any stale html version
    return localizedText === topic.text ? topic : { text: localizedText };
}
